name: Deploy docs

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-docs:
    name: Deploy docs
    if: github.repository == 'AmphoraProtocol/core'
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'Prod' || 'Dev' }}
      url: ${{ github.ref_name == 'main' && 'https://docs.amphorafinance.com' || 'https://docs.dev.amphorafinance.com' }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile --network-concurrency 1

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build Docs
        run: yarn docs:build

      - name: Create book folder
        run: mdbook build docs

      - uses: reggionick/s3-deploy@v3
        with:
          folder: docs/book
          bucket: ${{ secrets.DOCS_S3_BUCKET_NAME }}
          bucket-region: ${{ secrets.DOCS_S3_BUCKET_REGION }}
          dist-id: ${{ secrets.DOCS_CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: / *
          delete-removed: true
          private: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}