[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
single_line_statement_blocks = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first'

[profile.default]
solc = '0.8.14'
src = './solidity'
test = './solidity/test'
out = 'out'
libraries = []
cache = true
evm_version = 'london'
gas_reports = ['*']
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
verbosity = 0
fuzz_runs = 1000

[fuzz]
depth = 150

[invariant]
fail_on_revert = true

[profile.docs]
src = './solidity/contracts/'

[profile.coverage]
test = './solidity/test/unit'

[rpc_endpoints]
mainnet = "${MAINNET_RPC}"
goerli = "${GOERLI_RPC}"
